#! /bin/sh


test $# = 1 || { echo "Usage: newpost <title>"; exit 1; }

mkdir -p posts

> "posts/$1.html" \
printf '%s\n' "<style> body { line-height: 1.6; background: #dbdbdb; color: #222; } </style>" \
              "<pre>" "" ""   \
              "        # $1." \
              "" "    "

"${EDITOR:-:}" "posts/$1.html"
