#! /bin/bash


test $# = 1 || { echo "Usage: newpost <title>"; exit 1; }

mkdir -p posts

> "posts/$1.html" \
printf '%s\n' "<style> body { background: #BFB6BD; color: #0A1016; } </style>" \
              "<pre>" "" ""       \
              "            # $1." \
              "" "    "

"$EDITOR" "posts/$1.html"
